# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: false
    http_method_override: false
    handle_all_throwables: true
    default_locale: '%locale%'

    # see https://symfony.com/doc/current/deployment/proxies.html
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]

    translator:
        default_path: '%kernel.project_dir%/translations'

    serializer:
        enable_annotations: true

    php_errors:
        log: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    #session:
    #    handler_id: null
    #    cookie_secure: auto
    #    cookie_samesite: lax

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        profiler:
            collect: false
        cache:
            pools:
                app.version.cache:
                    adapter: cache.adapter.filesystem
