lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/%env(resolve:JWT_PRIVATE_KEY_PATH)%'
    public_key: '%kernel.project_dir%/%env(resolve:JWT_PUBLIC_KEY_PATH)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    # token extraction settings
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:                    # check token in a cookie
            enabled: true
            name:    BEARER
        query_parameter:           # check token in query string parameter
            enabled: true
            name:    bearer
