doctrine:
    dbal:
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'
            uuid_binary:  'Ramsey\Uuid\Doctrine\UuidBinaryType'
            uuid_binary_ordered_time: 'Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType'
        mapping_types:
            uuid_binary: 'binary'
            uuid_binary_ordered_time: 'binary'
