when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error

when@test:
    test_controllers:
        resource: '../../tests/E2E/Rest/Traits/Actions/src/'
        type: attribute

    test_life_cycle_controllers:
        resource: '../../tests/E2E/Rest/src/Controller'
        type: attribute
